name: Release

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, x86_64-pc-windows-gnu]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Install dependencies for Windows
        if: matrix.target == 'x86_64-pc-windows-gnu'
        run: sudo apt-get install -y gcc-mingw-w64-x86-64

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-binary
          path: target/${{ matrix.target }}/release/uuml${{ matrix.target == 'x86_64-pc-windows-gnu' && '.exe' || '' }}

  release:
    needs: build
    runs-on: ubuntu-24.04

    steps:
      - name: Download Windows binary
        uses: actions/download-artifact@v4
        with:
          name: x86_64-pc-windows-gnu-binary
          path: ./binaries

      - name: Download Linux binary
        uses: actions/download-artifact@v4
        with:
          name: x86_64-unknown-linux-gnu-binary
          path: ./binaries

      - name: Rename Windows binary
        run: mv ./binaries/uuml.exe ./binaries/uuml-win.exe

      - name: Rename Linux binary
        run: mv ./binaries/uuml ./binaries/uuml-linux

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v1
        with:
          files: ./binaries/*
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}